INSERT INTO
  TEST_ENTITY_CALENDAR (NAME, TYPE, CODE, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 3', 'TYPE', 'CODE', 'user3', 'user3');

INSERT INTO
  TEST_ENTITY_DATE (NAME, TYPE, CODE, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 4', 'TYP', 'C', 'user4', 'user4');

INSERT INTO
  TEST_ENTITY_OFFSET_DATE_TIME (NAME, TYPE, CODE, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 5', 'TY', 'CO', 'user5', 'user5');

INSERT INTO
  TEST_ENTITY_TIMESTAMP (NAME, TYPE, CODE, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 1', 'T', NULL, 'user1', 'user1');

INSERT INTO
  TEST_ENTITY_ZONED_DATE_TIME (NAME, TYPE, CODE, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 2', '', 'COD', 'user2', 'user2');
