INSERT INTO
  TEST_ENTITY_CALENDAR (NAME, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 3', 'user3', 'user3');

INSERT INTO
  TEST_ENTITY_DATE (NAME, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 4', 'user4', 'user4');

INSERT INTO
  TEST_ENTITY_OFFSET_DATE_TIME (NAME, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 5', 'user5', 'user5');

INSERT INTO
  TEST_ENTITY_TIMESTAMP (NAME, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 1', 'user1', 'user1');

INSERT INTO
  TEST_ENTITY_ZONED_DATE_TIME (NAME, CREATED_USER, UPDATED_USER)
VALUES
  ('Test Name 2', 'user2', 'user2');
