ALTER TABLE TEST_TABLE_1 MODIFY COLUMN CREATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TEST_TABLE_1 MODIFY COLUMN UPDATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
