ALTER TABLE TEST_ENTITY_TIMESTAMP MODIFY COLUMN CREATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TEST_ENTITY_TIMESTAMP MODIFY COLUMN UPDATED_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
